# Generated by Django 6.0.6 on 2026-06-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(max_length=20)),
                ('next_billing_date', models.DateField()),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
    ]
