# Generated by Django 6.0.6 on 2026-06-11 02:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_passwordotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordotp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
